postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  dbname: miniups

amazon:
  host: vcm-46755.vm.duke.edu
  port: 8080

ups:
  host: vcm-46755.vm.duke.edu
  port: 8080