// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: world_amazon-1.proto

package worldamazonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Description   *string                `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	Count         *int32                 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AProduct) Reset() {
	*x = AProduct{}
	mi := &file_world_amazon_1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AProduct) ProtoMessage() {}

func (x *AProduct) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AProduct.ProtoReflect.Descriptor instead.
func (*AProduct) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{0}
}

func (x *AProduct) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AProduct) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AProduct) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type AInitWarehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	X             *int32                 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AInitWarehouse) Reset() {
	*x = AInitWarehouse{}
	mi := &file_world_amazon_1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AInitWarehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AInitWarehouse) ProtoMessage() {}

func (x *AInitWarehouse) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AInitWarehouse.ProtoReflect.Descriptor instead.
func (*AInitWarehouse) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{1}
}

func (x *AInitWarehouse) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AInitWarehouse) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *AInitWarehouse) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type AConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worldid       *int64                 `protobuf:"varint,1,opt,name=worldid" json:"worldid,omitempty"`
	Initwh        []*AInitWarehouse      `protobuf:"bytes,2,rep,name=initwh" json:"initwh,omitempty"`
	IsAmazon      *bool                  `protobuf:"varint,3,req,name=isAmazon" json:"isAmazon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AConnect) Reset() {
	*x = AConnect{}
	mi := &file_world_amazon_1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AConnect) ProtoMessage() {}

func (x *AConnect) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AConnect.ProtoReflect.Descriptor instead.
func (*AConnect) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{2}
}

func (x *AConnect) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *AConnect) GetInitwh() []*AInitWarehouse {
	if x != nil {
		return x.Initwh
	}
	return nil
}

func (x *AConnect) GetIsAmazon() bool {
	if x != nil && x.IsAmazon != nil {
		return *x.IsAmazon
	}
	return false
}

type AConnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worldid       *int64                 `protobuf:"varint,1,req,name=worldid" json:"worldid,omitempty"`
	Result        *string                `protobuf:"bytes,2,req,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AConnected) Reset() {
	*x = AConnected{}
	mi := &file_world_amazon_1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AConnected) ProtoMessage() {}

func (x *AConnected) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AConnected.ProtoReflect.Descriptor instead.
func (*AConnected) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{3}
}

func (x *AConnected) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *AConnected) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type APack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Whnum         *int32                 `protobuf:"varint,1,req,name=whnum" json:"whnum,omitempty"`
	Things        []*AProduct            `protobuf:"bytes,2,rep,name=things" json:"things,omitempty"`
	Shipid        *int64                 `protobuf:"varint,3,req,name=shipid" json:"shipid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,4,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APack) Reset() {
	*x = APack{}
	mi := &file_world_amazon_1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APack) ProtoMessage() {}

func (x *APack) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APack.ProtoReflect.Descriptor instead.
func (*APack) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{4}
}

func (x *APack) GetWhnum() int32 {
	if x != nil && x.Whnum != nil {
		return *x.Whnum
	}
	return 0
}

func (x *APack) GetThings() []*AProduct {
	if x != nil {
		return x.Things
	}
	return nil
}

func (x *APack) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *APack) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APacked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipid        *int64                 `protobuf:"varint,1,req,name=shipid" json:"shipid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APacked) Reset() {
	*x = APacked{}
	mi := &file_world_amazon_1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APacked) ProtoMessage() {}

func (x *APacked) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APacked.ProtoReflect.Descriptor instead.
func (*APacked) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{5}
}

func (x *APacked) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *APacked) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type ALoaded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipid        *int64                 `protobuf:"varint,1,req,name=shipid" json:"shipid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ALoaded) Reset() {
	*x = ALoaded{}
	mi := &file_world_amazon_1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ALoaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALoaded) ProtoMessage() {}

func (x *ALoaded) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALoaded.ProtoReflect.Descriptor instead.
func (*ALoaded) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{6}
}

func (x *ALoaded) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *ALoaded) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APutOnTruck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Whnum         *int32                 `protobuf:"varint,1,req,name=whnum" json:"whnum,omitempty"`
	Truckid       *int32                 `protobuf:"varint,2,req,name=truckid" json:"truckid,omitempty"`
	Shipid        *int64                 `protobuf:"varint,3,req,name=shipid" json:"shipid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,4,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APutOnTruck) Reset() {
	*x = APutOnTruck{}
	mi := &file_world_amazon_1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APutOnTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APutOnTruck) ProtoMessage() {}

func (x *APutOnTruck) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APutOnTruck.ProtoReflect.Descriptor instead.
func (*APutOnTruck) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{7}
}

func (x *APutOnTruck) GetWhnum() int32 {
	if x != nil && x.Whnum != nil {
		return *x.Whnum
	}
	return 0
}

func (x *APutOnTruck) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *APutOnTruck) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *APutOnTruck) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APurchaseMore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Whnum         *int32                 `protobuf:"varint,1,req,name=whnum" json:"whnum,omitempty"`
	Things        []*AProduct            `protobuf:"bytes,2,rep,name=things" json:"things,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APurchaseMore) Reset() {
	*x = APurchaseMore{}
	mi := &file_world_amazon_1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APurchaseMore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APurchaseMore) ProtoMessage() {}

func (x *APurchaseMore) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APurchaseMore.ProtoReflect.Descriptor instead.
func (*APurchaseMore) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{8}
}

func (x *APurchaseMore) GetWhnum() int32 {
	if x != nil && x.Whnum != nil {
		return *x.Whnum
	}
	return 0
}

func (x *APurchaseMore) GetThings() []*AProduct {
	if x != nil {
		return x.Things
	}
	return nil
}

func (x *APurchaseMore) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type AErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *string                `protobuf:"bytes,1,req,name=err" json:"err,omitempty"`
	Originseqnum  *int64                 `protobuf:"varint,2,req,name=originseqnum" json:"originseqnum,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AErr) Reset() {
	*x = AErr{}
	mi := &file_world_amazon_1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AErr) ProtoMessage() {}

func (x *AErr) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AErr.ProtoReflect.Descriptor instead.
func (*AErr) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{9}
}

func (x *AErr) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *AErr) GetOriginseqnum() int64 {
	if x != nil && x.Originseqnum != nil {
		return *x.Originseqnum
	}
	return 0
}

func (x *AErr) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type AQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *int64                 `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AQuery) Reset() {
	*x = AQuery{}
	mi := &file_world_amazon_1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AQuery) ProtoMessage() {}

func (x *AQuery) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AQuery.ProtoReflect.Descriptor instead.
func (*AQuery) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{10}
}

func (x *AQuery) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *AQuery) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *int64                 `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	Status        *string                `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APackage) Reset() {
	*x = APackage{}
	mi := &file_world_amazon_1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APackage) ProtoMessage() {}

func (x *APackage) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APackage.ProtoReflect.Descriptor instead.
func (*APackage) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{11}
}

func (x *APackage) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *APackage) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *APackage) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type ACommands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buy           []*APurchaseMore       `protobuf:"bytes,1,rep,name=buy" json:"buy,omitempty"`
	Topack        []*APack               `protobuf:"bytes,2,rep,name=topack" json:"topack,omitempty"`
	Load          []*APutOnTruck         `protobuf:"bytes,3,rep,name=load" json:"load,omitempty"`
	Queries       []*AQuery              `protobuf:"bytes,4,rep,name=queries" json:"queries,omitempty"`
	Simspeed      *uint32                `protobuf:"varint,5,opt,name=simspeed" json:"simspeed,omitempty"`
	Disconnect    *bool                  `protobuf:"varint,6,opt,name=disconnect" json:"disconnect,omitempty"`
	Acks          []int64                `protobuf:"varint,7,rep,name=acks" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACommands) Reset() {
	*x = ACommands{}
	mi := &file_world_amazon_1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACommands) ProtoMessage() {}

func (x *ACommands) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACommands.ProtoReflect.Descriptor instead.
func (*ACommands) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{12}
}

func (x *ACommands) GetBuy() []*APurchaseMore {
	if x != nil {
		return x.Buy
	}
	return nil
}

func (x *ACommands) GetTopack() []*APack {
	if x != nil {
		return x.Topack
	}
	return nil
}

func (x *ACommands) GetLoad() []*APutOnTruck {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *ACommands) GetQueries() []*AQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ACommands) GetSimspeed() uint32 {
	if x != nil && x.Simspeed != nil {
		return *x.Simspeed
	}
	return 0
}

func (x *ACommands) GetDisconnect() bool {
	if x != nil && x.Disconnect != nil {
		return *x.Disconnect
	}
	return false
}

func (x *ACommands) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

type AResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arrived       []*APurchaseMore       `protobuf:"bytes,1,rep,name=arrived" json:"arrived,omitempty"`
	Ready         []*APacked             `protobuf:"bytes,2,rep,name=ready" json:"ready,omitempty"`
	Loaded        []*ALoaded             `protobuf:"bytes,3,rep,name=loaded" json:"loaded,omitempty"`
	Finished      *bool                  `protobuf:"varint,4,opt,name=finished" json:"finished,omitempty"`
	Error         []*AErr                `protobuf:"bytes,5,rep,name=error" json:"error,omitempty"`
	Acks          []int64                `protobuf:"varint,6,rep,name=acks" json:"acks,omitempty"`
	Packagestatus []*APackage            `protobuf:"bytes,7,rep,name=packagestatus" json:"packagestatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AResponses) Reset() {
	*x = AResponses{}
	mi := &file_world_amazon_1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AResponses) ProtoMessage() {}

func (x *AResponses) ProtoReflect() protoreflect.Message {
	mi := &file_world_amazon_1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AResponses.ProtoReflect.Descriptor instead.
func (*AResponses) Descriptor() ([]byte, []int) {
	return file_world_amazon_1_proto_rawDescGZIP(), []int{13}
}

func (x *AResponses) GetArrived() []*APurchaseMore {
	if x != nil {
		return x.Arrived
	}
	return nil
}

func (x *AResponses) GetReady() []*APacked {
	if x != nil {
		return x.Ready
	}
	return nil
}

func (x *AResponses) GetLoaded() []*ALoaded {
	if x != nil {
		return x.Loaded
	}
	return nil
}

func (x *AResponses) GetFinished() bool {
	if x != nil && x.Finished != nil {
		return *x.Finished
	}
	return false
}

func (x *AResponses) GetError() []*AErr {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AResponses) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *AResponses) GetPackagestatus() []*APackage {
	if x != nil {
		return x.Packagestatus
	}
	return nil
}

var File_world_amazon_1_proto protoreflect.FileDescriptor

const file_world_amazon_1_proto_rawDesc = "" +
	"\n" +
	"\x14world_amazon-1.proto\"R\n" +
	"\bAProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x02(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x03 \x02(\x05R\x05count\"<\n" +
	"\x0eAInitWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x02(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x02(\x05R\x01y\"i\n" +
	"\bAConnect\x12\x18\n" +
	"\aworldid\x18\x01 \x01(\x03R\aworldid\x12'\n" +
	"\x06initwh\x18\x02 \x03(\v2\x0f.AInitWarehouseR\x06initwh\x12\x1a\n" +
	"\bisAmazon\x18\x03 \x02(\bR\bisAmazon\">\n" +
	"\n" +
	"AConnected\x12\x18\n" +
	"\aworldid\x18\x01 \x02(\x03R\aworldid\x12\x16\n" +
	"\x06result\x18\x02 \x02(\tR\x06result\"p\n" +
	"\x05APack\x12\x14\n" +
	"\x05whnum\x18\x01 \x02(\x05R\x05whnum\x12!\n" +
	"\x06things\x18\x02 \x03(\v2\t.AProductR\x06things\x12\x16\n" +
	"\x06shipid\x18\x03 \x02(\x03R\x06shipid\x12\x16\n" +
	"\x06seqnum\x18\x04 \x02(\x03R\x06seqnum\"9\n" +
	"\aAPacked\x12\x16\n" +
	"\x06shipid\x18\x01 \x02(\x03R\x06shipid\x12\x16\n" +
	"\x06seqnum\x18\x02 \x02(\x03R\x06seqnum\"9\n" +
	"\aALoaded\x12\x16\n" +
	"\x06shipid\x18\x01 \x02(\x03R\x06shipid\x12\x16\n" +
	"\x06seqnum\x18\x02 \x02(\x03R\x06seqnum\"m\n" +
	"\vAPutOnTruck\x12\x14\n" +
	"\x05whnum\x18\x01 \x02(\x05R\x05whnum\x12\x18\n" +
	"\atruckid\x18\x02 \x02(\x05R\atruckid\x12\x16\n" +
	"\x06shipid\x18\x03 \x02(\x03R\x06shipid\x12\x16\n" +
	"\x06seqnum\x18\x04 \x02(\x03R\x06seqnum\"`\n" +
	"\rAPurchaseMore\x12\x14\n" +
	"\x05whnum\x18\x01 \x02(\x05R\x05whnum\x12!\n" +
	"\x06things\x18\x02 \x03(\v2\t.AProductR\x06things\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\"T\n" +
	"\x04AErr\x12\x10\n" +
	"\x03err\x18\x01 \x02(\tR\x03err\x12\"\n" +
	"\foriginseqnum\x18\x02 \x02(\x03R\foriginseqnum\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\">\n" +
	"\x06AQuery\x12\x1c\n" +
	"\tpackageid\x18\x01 \x02(\x03R\tpackageid\x12\x16\n" +
	"\x06seqnum\x18\x02 \x02(\x03R\x06seqnum\"X\n" +
	"\bAPackage\x12\x1c\n" +
	"\tpackageid\x18\x01 \x02(\x03R\tpackageid\x12\x16\n" +
	"\x06status\x18\x02 \x02(\tR\x06status\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\"\xe2\x01\n" +
	"\tACommands\x12 \n" +
	"\x03buy\x18\x01 \x03(\v2\x0e.APurchaseMoreR\x03buy\x12\x1e\n" +
	"\x06topack\x18\x02 \x03(\v2\x06.APackR\x06topack\x12 \n" +
	"\x04load\x18\x03 \x03(\v2\f.APutOnTruckR\x04load\x12!\n" +
	"\aqueries\x18\x04 \x03(\v2\a.AQueryR\aqueries\x12\x1a\n" +
	"\bsimspeed\x18\x05 \x01(\rR\bsimspeed\x12\x1e\n" +
	"\n" +
	"disconnect\x18\x06 \x01(\bR\n" +
	"disconnect\x12\x12\n" +
	"\x04acks\x18\a \x03(\x03R\x04acks\"\xf6\x01\n" +
	"\n" +
	"AResponses\x12(\n" +
	"\aarrived\x18\x01 \x03(\v2\x0e.APurchaseMoreR\aarrived\x12\x1e\n" +
	"\x05ready\x18\x02 \x03(\v2\b.APackedR\x05ready\x12 \n" +
	"\x06loaded\x18\x03 \x03(\v2\b.ALoadedR\x06loaded\x12\x1a\n" +
	"\bfinished\x18\x04 \x01(\bR\bfinished\x12\x1b\n" +
	"\x05error\x18\x05 \x03(\v2\x05.AErrR\x05error\x12\x12\n" +
	"\x04acks\x18\x06 \x03(\x03R\x04acks\x12/\n" +
	"\rpackagestatus\x18\a \x03(\v2\t.APackageR\rpackagestatus"

var (
	file_world_amazon_1_proto_rawDescOnce sync.Once
	file_world_amazon_1_proto_rawDescData []byte
)

func file_world_amazon_1_proto_rawDescGZIP() []byte {
	file_world_amazon_1_proto_rawDescOnce.Do(func() {
		file_world_amazon_1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_amazon_1_proto_rawDesc), len(file_world_amazon_1_proto_rawDesc)))
	})
	return file_world_amazon_1_proto_rawDescData
}

var file_world_amazon_1_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_world_amazon_1_proto_goTypes = []any{
	(*AProduct)(nil),       // 0: AProduct
	(*AInitWarehouse)(nil), // 1: AInitWarehouse
	(*AConnect)(nil),       // 2: AConnect
	(*AConnected)(nil),     // 3: AConnected
	(*APack)(nil),          // 4: APack
	(*APacked)(nil),        // 5: APacked
	(*ALoaded)(nil),        // 6: ALoaded
	(*APutOnTruck)(nil),    // 7: APutOnTruck
	(*APurchaseMore)(nil),  // 8: APurchaseMore
	(*AErr)(nil),           // 9: AErr
	(*AQuery)(nil),         // 10: AQuery
	(*APackage)(nil),       // 11: APackage
	(*ACommands)(nil),      // 12: ACommands
	(*AResponses)(nil),     // 13: AResponses
}
var file_world_amazon_1_proto_depIdxs = []int32{
	1,  // 0: AConnect.initwh:type_name -> AInitWarehouse
	0,  // 1: APack.things:type_name -> AProduct
	0,  // 2: APurchaseMore.things:type_name -> AProduct
	8,  // 3: ACommands.buy:type_name -> APurchaseMore
	4,  // 4: ACommands.topack:type_name -> APack
	7,  // 5: ACommands.load:type_name -> APutOnTruck
	10, // 6: ACommands.queries:type_name -> AQuery
	8,  // 7: AResponses.arrived:type_name -> APurchaseMore
	5,  // 8: AResponses.ready:type_name -> APacked
	6,  // 9: AResponses.loaded:type_name -> ALoaded
	9,  // 10: AResponses.error:type_name -> AErr
	11, // 11: AResponses.packagestatus:type_name -> APackage
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_world_amazon_1_proto_init() }
func file_world_amazon_1_proto_init() {
	if File_world_amazon_1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_amazon_1_proto_rawDesc), len(file_world_amazon_1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_world_amazon_1_proto_goTypes,
		DependencyIndexes: file_world_amazon_1_proto_depIdxs,
		MessageInfos:      file_world_amazon_1_proto_msgTypes,
	}.Build()
	File_world_amazon_1_proto = out.File
	file_world_amazon_1_proto_goTypes = nil
	file_world_amazon_1_proto_depIdxs = nil
}
