// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: world_ups-1.proto

package worldupspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UInitTruck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	X             *int32                 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UInitTruck) Reset() {
	*x = UInitTruck{}
	mi := &file_world_ups_1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInitTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInitTruck) ProtoMessage() {}

func (x *UInitTruck) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInitTruck.ProtoReflect.Descriptor instead.
func (*UInitTruck) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{0}
}

func (x *UInitTruck) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UInitTruck) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UInitTruck) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type UConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worldid       *int64                 `protobuf:"varint,1,opt,name=worldid" json:"worldid,omitempty"`
	Trucks        []*UInitTruck          `protobuf:"bytes,2,rep,name=trucks" json:"trucks,omitempty"`
	IsAmazon      *bool                  `protobuf:"varint,3,req,name=isAmazon" json:"isAmazon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UConnect) Reset() {
	*x = UConnect{}
	mi := &file_world_ups_1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UConnect) ProtoMessage() {}

func (x *UConnect) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UConnect.ProtoReflect.Descriptor instead.
func (*UConnect) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{1}
}

func (x *UConnect) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *UConnect) GetTrucks() []*UInitTruck {
	if x != nil {
		return x.Trucks
	}
	return nil
}

func (x *UConnect) GetIsAmazon() bool {
	if x != nil && x.IsAmazon != nil {
		return *x.IsAmazon
	}
	return false
}

type UConnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worldid       *int64                 `protobuf:"varint,1,req,name=worldid" json:"worldid,omitempty"`
	Result        *string                `protobuf:"bytes,2,req,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UConnected) Reset() {
	*x = UConnected{}
	mi := &file_world_ups_1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UConnected) ProtoMessage() {}

func (x *UConnected) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UConnected.ProtoReflect.Descriptor instead.
func (*UConnected) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{2}
}

func (x *UConnected) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *UConnected) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type UGoPickup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truckid       *int32                 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Whid          *int32                 `protobuf:"varint,2,req,name=whid" json:"whid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UGoPickup) Reset() {
	*x = UGoPickup{}
	mi := &file_world_ups_1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UGoPickup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UGoPickup) ProtoMessage() {}

func (x *UGoPickup) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UGoPickup.ProtoReflect.Descriptor instead.
func (*UGoPickup) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{3}
}

func (x *UGoPickup) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UGoPickup) GetWhid() int32 {
	if x != nil && x.Whid != nil {
		return *x.Whid
	}
	return 0
}

func (x *UGoPickup) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truckid       *int32                 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	X             *int32                 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	Status        *string                `protobuf:"bytes,4,req,name=status" json:"status,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,5,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UFinished) Reset() {
	*x = UFinished{}
	mi := &file_world_ups_1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UFinished) ProtoMessage() {}

func (x *UFinished) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UFinished.ProtoReflect.Descriptor instead.
func (*UFinished) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{4}
}

func (x *UFinished) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UFinished) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UFinished) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *UFinished) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UFinished) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UDeliveryMade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truckid       *int32                 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packageid     *int64                 `protobuf:"varint,2,req,name=packageid" json:"packageid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDeliveryMade) Reset() {
	*x = UDeliveryMade{}
	mi := &file_world_ups_1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDeliveryMade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDeliveryMade) ProtoMessage() {}

func (x *UDeliveryMade) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDeliveryMade.ProtoReflect.Descriptor instead.
func (*UDeliveryMade) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{5}
}

func (x *UDeliveryMade) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UDeliveryMade) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *UDeliveryMade) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UDeliveryLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *int64                 `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	X             *int32                 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDeliveryLocation) Reset() {
	*x = UDeliveryLocation{}
	mi := &file_world_ups_1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDeliveryLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDeliveryLocation) ProtoMessage() {}

func (x *UDeliveryLocation) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDeliveryLocation.ProtoReflect.Descriptor instead.
func (*UDeliveryLocation) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{6}
}

func (x *UDeliveryLocation) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *UDeliveryLocation) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UDeliveryLocation) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type UGoDeliver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truckid       *int32                 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packages      []*UDeliveryLocation   `protobuf:"bytes,2,rep,name=packages" json:"packages,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UGoDeliver) Reset() {
	*x = UGoDeliver{}
	mi := &file_world_ups_1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UGoDeliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UGoDeliver) ProtoMessage() {}

func (x *UGoDeliver) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UGoDeliver.ProtoReflect.Descriptor instead.
func (*UGoDeliver) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{7}
}

func (x *UGoDeliver) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UGoDeliver) GetPackages() []*UDeliveryLocation {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *UGoDeliver) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *string                `protobuf:"bytes,1,req,name=err" json:"err,omitempty"`
	Originseqnum  *int64                 `protobuf:"varint,2,req,name=originseqnum" json:"originseqnum,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UErr) Reset() {
	*x = UErr{}
	mi := &file_world_ups_1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UErr) ProtoMessage() {}

func (x *UErr) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UErr.ProtoReflect.Descriptor instead.
func (*UErr) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{8}
}

func (x *UErr) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *UErr) GetOriginseqnum() int64 {
	if x != nil && x.Originseqnum != nil {
		return *x.Originseqnum
	}
	return 0
}

func (x *UErr) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truckid       *int32                 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UQuery) Reset() {
	*x = UQuery{}
	mi := &file_world_ups_1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UQuery) ProtoMessage() {}

func (x *UQuery) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UQuery.ProtoReflect.Descriptor instead.
func (*UQuery) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{9}
}

func (x *UQuery) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UQuery) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UTruck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truckid       *int32                 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Status        *string                `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	X             *int32                 `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	Seqnum        *int64                 `protobuf:"varint,5,req,name=seqnum" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTruck) Reset() {
	*x = UTruck{}
	mi := &file_world_ups_1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTruck) ProtoMessage() {}

func (x *UTruck) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTruck.ProtoReflect.Descriptor instead.
func (*UTruck) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{10}
}

func (x *UTruck) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UTruck) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UTruck) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UTruck) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *UTruck) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UCommands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pickups       []*UGoPickup           `protobuf:"bytes,1,rep,name=pickups" json:"pickups,omitempty"`
	Deliveries    []*UGoDeliver          `protobuf:"bytes,2,rep,name=deliveries" json:"deliveries,omitempty"`
	Simspeed      *uint32                `protobuf:"varint,3,opt,name=simspeed" json:"simspeed,omitempty"`
	Disconnect    *bool                  `protobuf:"varint,4,opt,name=disconnect" json:"disconnect,omitempty"`
	Queries       []*UQuery              `protobuf:"bytes,5,rep,name=queries" json:"queries,omitempty"`
	Acks          []int64                `protobuf:"varint,6,rep,name=acks" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UCommands) Reset() {
	*x = UCommands{}
	mi := &file_world_ups_1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UCommands) ProtoMessage() {}

func (x *UCommands) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UCommands.ProtoReflect.Descriptor instead.
func (*UCommands) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{11}
}

func (x *UCommands) GetPickups() []*UGoPickup {
	if x != nil {
		return x.Pickups
	}
	return nil
}

func (x *UCommands) GetDeliveries() []*UGoDeliver {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *UCommands) GetSimspeed() uint32 {
	if x != nil && x.Simspeed != nil {
		return *x.Simspeed
	}
	return 0
}

func (x *UCommands) GetDisconnect() bool {
	if x != nil && x.Disconnect != nil {
		return *x.Disconnect
	}
	return false
}

func (x *UCommands) GetQueries() []*UQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *UCommands) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

type UResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completions   []*UFinished           `protobuf:"bytes,1,rep,name=completions" json:"completions,omitempty"`
	Delivered     []*UDeliveryMade       `protobuf:"bytes,2,rep,name=delivered" json:"delivered,omitempty"`
	Finished      *bool                  `protobuf:"varint,3,opt,name=finished" json:"finished,omitempty"`
	Acks          []int64                `protobuf:"varint,4,rep,name=acks" json:"acks,omitempty"`
	Truckstatus   []*UTruck              `protobuf:"bytes,5,rep,name=truckstatus" json:"truckstatus,omitempty"`
	Error         []*UErr                `protobuf:"bytes,6,rep,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UResponses) Reset() {
	*x = UResponses{}
	mi := &file_world_ups_1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UResponses) ProtoMessage() {}

func (x *UResponses) ProtoReflect() protoreflect.Message {
	mi := &file_world_ups_1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UResponses.ProtoReflect.Descriptor instead.
func (*UResponses) Descriptor() ([]byte, []int) {
	return file_world_ups_1_proto_rawDescGZIP(), []int{12}
}

func (x *UResponses) GetCompletions() []*UFinished {
	if x != nil {
		return x.Completions
	}
	return nil
}

func (x *UResponses) GetDelivered() []*UDeliveryMade {
	if x != nil {
		return x.Delivered
	}
	return nil
}

func (x *UResponses) GetFinished() bool {
	if x != nil && x.Finished != nil {
		return *x.Finished
	}
	return false
}

func (x *UResponses) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *UResponses) GetTruckstatus() []*UTruck {
	if x != nil {
		return x.Truckstatus
	}
	return nil
}

func (x *UResponses) GetError() []*UErr {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_world_ups_1_proto protoreflect.FileDescriptor

const file_world_ups_1_proto_rawDesc = "" +
	"\n" +
	"\x11world_ups-1.proto\"8\n" +
	"\n" +
	"UInitTruck\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x02(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x02(\x05R\x01y\"e\n" +
	"\bUConnect\x12\x18\n" +
	"\aworldid\x18\x01 \x01(\x03R\aworldid\x12#\n" +
	"\x06trucks\x18\x02 \x03(\v2\v.UInitTruckR\x06trucks\x12\x1a\n" +
	"\bisAmazon\x18\x03 \x02(\bR\bisAmazon\">\n" +
	"\n" +
	"UConnected\x12\x18\n" +
	"\aworldid\x18\x01 \x02(\x03R\aworldid\x12\x16\n" +
	"\x06result\x18\x02 \x02(\tR\x06result\"Q\n" +
	"\tUGoPickup\x12\x18\n" +
	"\atruckid\x18\x01 \x02(\x05R\atruckid\x12\x12\n" +
	"\x04whid\x18\x02 \x02(\x05R\x04whid\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\"q\n" +
	"\tUFinished\x12\x18\n" +
	"\atruckid\x18\x01 \x02(\x05R\atruckid\x12\f\n" +
	"\x01x\x18\x02 \x02(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x02(\x05R\x01y\x12\x16\n" +
	"\x06status\x18\x04 \x02(\tR\x06status\x12\x16\n" +
	"\x06seqnum\x18\x05 \x02(\x03R\x06seqnum\"_\n" +
	"\rUDeliveryMade\x12\x18\n" +
	"\atruckid\x18\x01 \x02(\x05R\atruckid\x12\x1c\n" +
	"\tpackageid\x18\x02 \x02(\x03R\tpackageid\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\"M\n" +
	"\x11UDeliveryLocation\x12\x1c\n" +
	"\tpackageid\x18\x01 \x02(\x03R\tpackageid\x12\f\n" +
	"\x01x\x18\x02 \x02(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x02(\x05R\x01y\"n\n" +
	"\n" +
	"UGoDeliver\x12\x18\n" +
	"\atruckid\x18\x01 \x02(\x05R\atruckid\x12.\n" +
	"\bpackages\x18\x02 \x03(\v2\x12.UDeliveryLocationR\bpackages\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\"T\n" +
	"\x04UErr\x12\x10\n" +
	"\x03err\x18\x01 \x02(\tR\x03err\x12\"\n" +
	"\foriginseqnum\x18\x02 \x02(\x03R\foriginseqnum\x12\x16\n" +
	"\x06seqnum\x18\x03 \x02(\x03R\x06seqnum\":\n" +
	"\x06UQuery\x12\x18\n" +
	"\atruckid\x18\x01 \x02(\x05R\atruckid\x12\x16\n" +
	"\x06seqnum\x18\x02 \x02(\x03R\x06seqnum\"n\n" +
	"\x06UTruck\x12\x18\n" +
	"\atruckid\x18\x01 \x02(\x05R\atruckid\x12\x16\n" +
	"\x06status\x18\x02 \x02(\tR\x06status\x12\f\n" +
	"\x01x\x18\x03 \x02(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x02(\x05R\x01y\x12\x16\n" +
	"\x06seqnum\x18\x05 \x02(\x03R\x06seqnum\"\xd1\x01\n" +
	"\tUCommands\x12$\n" +
	"\apickups\x18\x01 \x03(\v2\n" +
	".UGoPickupR\apickups\x12+\n" +
	"\n" +
	"deliveries\x18\x02 \x03(\v2\v.UGoDeliverR\n" +
	"deliveries\x12\x1a\n" +
	"\bsimspeed\x18\x03 \x01(\rR\bsimspeed\x12\x1e\n" +
	"\n" +
	"disconnect\x18\x04 \x01(\bR\n" +
	"disconnect\x12!\n" +
	"\aqueries\x18\x05 \x03(\v2\a.UQueryR\aqueries\x12\x12\n" +
	"\x04acks\x18\x06 \x03(\x03R\x04acks\"\xe0\x01\n" +
	"\n" +
	"UResponses\x12,\n" +
	"\vcompletions\x18\x01 \x03(\v2\n" +
	".UFinishedR\vcompletions\x12,\n" +
	"\tdelivered\x18\x02 \x03(\v2\x0e.UDeliveryMadeR\tdelivered\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\x12\x12\n" +
	"\x04acks\x18\x04 \x03(\x03R\x04acks\x12)\n" +
	"\vtruckstatus\x18\x05 \x03(\v2\a.UTruckR\vtruckstatus\x12\x1b\n" +
	"\x05error\x18\x06 \x03(\v2\x05.UErrR\x05error"

var (
	file_world_ups_1_proto_rawDescOnce sync.Once
	file_world_ups_1_proto_rawDescData []byte
)

func file_world_ups_1_proto_rawDescGZIP() []byte {
	file_world_ups_1_proto_rawDescOnce.Do(func() {
		file_world_ups_1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_ups_1_proto_rawDesc), len(file_world_ups_1_proto_rawDesc)))
	})
	return file_world_ups_1_proto_rawDescData
}

var file_world_ups_1_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_world_ups_1_proto_goTypes = []any{
	(*UInitTruck)(nil),        // 0: UInitTruck
	(*UConnect)(nil),          // 1: UConnect
	(*UConnected)(nil),        // 2: UConnected
	(*UGoPickup)(nil),         // 3: UGoPickup
	(*UFinished)(nil),         // 4: UFinished
	(*UDeliveryMade)(nil),     // 5: UDeliveryMade
	(*UDeliveryLocation)(nil), // 6: UDeliveryLocation
	(*UGoDeliver)(nil),        // 7: UGoDeliver
	(*UErr)(nil),              // 8: UErr
	(*UQuery)(nil),            // 9: UQuery
	(*UTruck)(nil),            // 10: UTruck
	(*UCommands)(nil),         // 11: UCommands
	(*UResponses)(nil),        // 12: UResponses
}
var file_world_ups_1_proto_depIdxs = []int32{
	0,  // 0: UConnect.trucks:type_name -> UInitTruck
	6,  // 1: UGoDeliver.packages:type_name -> UDeliveryLocation
	3,  // 2: UCommands.pickups:type_name -> UGoPickup
	7,  // 3: UCommands.deliveries:type_name -> UGoDeliver
	9,  // 4: UCommands.queries:type_name -> UQuery
	4,  // 5: UResponses.completions:type_name -> UFinished
	5,  // 6: UResponses.delivered:type_name -> UDeliveryMade
	10, // 7: UResponses.truckstatus:type_name -> UTruck
	8,  // 8: UResponses.error:type_name -> UErr
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_world_ups_1_proto_init() }
func file_world_ups_1_proto_init() {
	if File_world_ups_1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_ups_1_proto_rawDesc), len(file_world_ups_1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_world_ups_1_proto_goTypes,
		DependencyIndexes: file_world_ups_1_proto_depIdxs,
		MessageInfos:      file_world_ups_1_proto_msgTypes,
	}.Build()
	File_world_ups_1_proto = out.File
	file_world_ups_1_proto_goTypes = nil
	file_world_ups_1_proto_depIdxs = nil
}
